### ISSUE TITLE
how make in kali linux

### ISSUE THREAD

**Issue by hktalent** [katmagic/Shallot#39]
```
# ./configure && make
Liunx detected.  Have you considered switching to BSD?
Configuration successful.  This does not mean it will build.
If you are missing gcc, or required libraries/headers, you
will need to install them first.
cc  -O3 -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib  -Wall -o src/math.o -c src/math.c
src/math.c: In function ‘easygen’:
src/math.c:30:5: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
     rsa = RSA_generate_key(num, 3, NULL, NULL);
     ^~~
In file included from /usr/include/openssl/asn1.h:15,
                 from /usr/include/openssl/rsa.h:16,
                 from src/math.h:24,
                 from src/math.c:3:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^~~~~~~~~~~~~~~~~~
src/math.c: In function ‘sane_key’:
src/math.c:67:17: error: dereferencing pointer to incomplete type ‘RSA’ {aka ‘struct rsa_st’}
   BN_sub(p1, rsa->p, BN_value_one()); // p - 1
                 ^~
src/math.c:78:10: error: dereferencing pointer to incomplete type ‘BIGNUM’ {aka ‘struct bignum_st’}
   if(!chk->neg)
          ^~
make: *** [Makefile:44: src/math.o] Error 1
```

**Comment by VipeOut23** [comment]
You should be able to compile this fork https://github.com/katmagic/Shallot/pull/37

**Comment by itJunky** [comment]
Have a same error on linux ubuntu with latest master.

How can i fix it?

**Comment by VipeOut23** [comment]
@itJunky you need to checkout the "openssl-api-changes" branch from my fork.
`git pull https://github.com/VipeOut23/shallot ; git checkout openssl-api-changes`

**Comment by hktalent** [comment]
@VipeOut23  @itJunky 
use:
https://github.com/hktalent/shallot_eschalot

**Comment by VipeOut23** [comment]
@hktalent but who want's to use distributed binaries and openssl 1.0, meh. Still https://github.com/lachesis/scallion might be the best way to go.

**Comment by itJunky** [comment]
Why i need use some other branches? Where write about it in documentation?

Scallion is more shity software, because need giant mono and some strange msbuild, but it doesn't exist on linux...

I found normal working project eschalot who start without dancing with a tambourine like in this project or scallion.

**Comment by hktalent** [comment]
@VipeOut23 
If you don't code security auditing, use code to compile, and use binary files to make a difference?

**Comment by VipeOut23** [comment]
@hktalent yeah that's true, but if you have an established project with different people working on it you have kind of an confirmation that it is likely secure.

**Comment by hktalent** [comment]
@VipeOut23 @itJunky
run it in docker
https://github.com/hktalent/shallot_eschalot

**Comment by th4l1x** [comment]
@jroeger23 solution worked fine on ubuntu 20.04 thanks!
previous i have installed some packages
```
sudo apt install -y \
build-essential \
libssl-dev \
libcurl4-openssl-dev \
libsodium-dev \
autoconf
```
